project_id = "trwalgesbwfsvxincldg"

[functions.approve-deposit]
verify_jwt = false

[functions.approve-withdrawal]
verify_jwt = false

[functions.daily-interest]
verify_jwt = false

[functions.release-collateral]
verify_jwt = false

[functions.check-defaults]
verify_jwt = false

[functions.request-loan]
verify_jwt = false

[functions.fund-loan]
verify_jwt = false

[functions.repay-loan]
verify_jwt = false

[functions.manage-loan]
verify_jwt = false

[functions.seed-governor]
verify_jwt = false
